FROM    debian:buster

RUN	    apt-get update && apt-get -y upgrade \
	        && apt-get -y install mariadb-server vim procps

COPY    ./conf/50-server.cnf /etc/mysql/mariadb.conf.d/50-server.cnf
COPY    ./tools/entrypoint.sh /tmp/entrypoint.sh

EXPOSE	3306

RUN     chmod +x /tmp/entrypoint.sh

ENTRYPOINT  ["./tmp/entrypoint.sh"]